branches:
  only:
    - 'master'
    - 'dev'
language: ruby
rvm:
  - 1.9.2
  - 1.9.3

env:
  - DB=postgres

bundler_args: "--without assets:development:production"
before_script: bundle exec rake db:create db:migrate

notifications:
  irc:
    channels:
      - 'irc.freenode.org:6667#codeforamerica'

