common: &common
  adapter: postgresql
  username: postgres
  password: postgres # from psql setup, see Postgresql

development:
  <<: *common
  database: textyourcity_dev
  host: localhost


test:
  <<: *common
  database: textyourcity_test
  host: localhost

production:
  <<: *common
  database: textyourcity_production
