common: &common
  adapter: postgresql
  username: postgres
  password: postgres # from psql setup, see Postgresql

development:
  <<: *common
  database: textyourcity_dev

test:
  <<: *common
  database: textyourcity_test

production:
  <<: *common
  database: textyourcity_production